server:
  port: 9090
#  servlet:
#    context-path: /reimbursements

# for actuator --> localhost/reimbursements/actuator/metrics
# can then query for more info --> localhost/reimbursements/actuator/metrics/process.start.time
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://34.69.173.81:3306/ReimbursementApp
  # allows capitalization for your tables
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl